version: "3.1"

services:
  nest_app:
    container_name: nest_app
    image: node:14
    working_dir: /usr/src/app
    command: ["npm", "run", "start:dev"]
    restart: on-failure
    environment:
      NODE_ENV: dev
      PG_USER: postgres
      PG_PWD: postgres
      DB_HOST: postgres
      DB_NAME: nest-poc
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      ELASTIC_HOST: http://elasticsearch:9200
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
      - elasticsearch

  postgres:
    container_name: nest_app_postgres
    image: postgres:10.6
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: nest_app_redis
    image: redis
    expose:
      - 6379
    volumes:
      - redis:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: nest_app_elasticsearch
    restart: unless-stopped
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  postgres:
  redis:
  elasticsearch-data:
