version: "3.1"

services:
  nest_app:
    container_name: nest_app
    image: node:14
    working_dir: /usr/src/app
    command: ["npm", "run", "start:dev"]
    restart: on-failure
    environment:
      NODE_ENV: dev
      PG_USER: postgres
      PG_PWD: postgres
      DB_HOST: postgres
      DB_NAME: nest-poc
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: nest_app_postgres
    image: postgres:10.6
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: nest_app_redis
    image: redis
    expose:
      - 6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
